services:
  testdevops:
    container_name: testdevops
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql;Database=${DB_NAME};User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True
    depends_on:
      - sql

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022-testdevops
    ports:
      - "1436:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: